version: "3"

services:
  docker-registry:
    container_name: docker-registry
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    volumes:
      - regiser-volume:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true
  docker-registry-ui:
    container_name: docker-registry-ui
    image: konradkleine/docker-registry-frontend:v2
    platform: linux/amd64
    ports:
      - 8080:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
volumes:
  regiser-volume:
